services:
  - type: web
    name: rtb-document-planner
    env: python
    region: oregon
    buildCommand: "cd backend && pip install -r requirements.txt && python create_db.py"
    startCommand: "cd backend && python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
