services:
  - type: web
    name: rtb-document-planner
    env: python
    region: oregon
    buildCommand: "pip install -r backend/requirements.txt && python backend/create_db.py"
    startCommand: "cd backend && python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
