from docx import Document

print('=== SESSION PLAN VERIFICATION ===')
doc = Document('FINAL_TEST_Session_Plan.docx')
print(f'Total tables: {len(doc.tables)}')
print(f'Table 0 (Header): {len(doc.tables[0].rows)} rows, {len(doc.tables[0].rows[0].cells)} cols')
print(f'School name: {doc.tables[0].rows[0].cells[1].paragraphs[0].runs[0].text}')
print(f'Location is bold: {doc.tables[0].rows[0].cells[1].paragraphs[0].runs[1].font.bold}')
print(f'Table 1 (Main): {len(doc.tables[1].rows)} rows')
print(f'Row 0: {doc.tables[1].rows[0].cells[0].text[:40]}')
print(f'Row 3 (LO): {doc.tables[1].rows[3].cells[1].text[:50]}...')
print('SESSION PLAN: OK\n')

print('=== SCHEME OF WORK VERIFICATION ===')
doc2 = Document('FINAL_TEST_Scheme_of_Work.docx')
print(f'Total tables: {len(doc2.tables)}')
print(f'Table 1 (Info): Date = {doc2.tables[1].rows[7].cells[1].text}')
print(f'Table 2 (Term 1): {len(doc2.tables[2].rows)} rows, {len(doc2.tables[2].rows[0].cells)} cols')
print('Term 1 Row 0 headers:')
for i in range(min(9, len(doc2.tables[2].rows[0].cells))):
    print(f'  Col {i}: {doc2.tables[2].rows[0].cells[i].text[:25]}')
print('\nTerm 1 Data Row 2:')
print(f'  Weeks: {doc2.tables[2].rows[2].cells[0].text}')
print(f'  LO: {doc2.tables[2].rows[2].cells[1].text[:40]}...')
print(f'  Duration: {doc2.tables[2].rows[2].cells[2].text}')
print(f'  Activities: {doc2.tables[2].rows[2].cells[4].text[:30]}...')
print(f'  Resources: {doc2.tables[2].rows[2].cells[5].text[:30]}...')
print(f'  Assessment: {doc2.tables[2].rows[2].cells[6].text[:30]}...')
print(f'  Place: {doc2.tables[2].rows[2].cells[7].text}')
print('\nSCHEME OF WORK: OK - All 9 columns filled!')
